### ISSUE TITLE
Feature request: Event notifications 

### ISSUE THREAD

**Issue by cybersholt** [sp-engineering/frigate-viewer#2]
Recently started using Frigate and found this app, it would be awesome if there was a setting that could be toggled that enabled notifications whenever an event occurs. 

Possibly could also filter the events to only get notifications for person for example.

**Comment by cybersholt** [comment]
@piwko28 Thanks for the detailed response, I was surprised myself that they don't have any API for this. I was thinking the app may be able to do something since it has access to the events, sort of like check every 5 minutes, if the event count has increased send notification. Obviously there are several ways to get there. 

Right now what I use is
[docker-wyze-bridge](https://github.com/mrlt8/docker-wyze-bridge) to generate my camera feeds, it then supports [ntfy.sh](https://ntfy.sh/)  which is pretty cool universal notification platform.

Anyways Thanks again for the feedback and keep up the great work!

P.S. Any plans on releasing an iOS version? I'd love to have this for my iPad.

**Comment by maxdd** [comment]
I was also looking into this particularly to receive notifications over telegram for example.
I was thinking of adding a telegram.py to handle the notification directly inside of frigate comms since the main issue is that polling is really terrible for this use case.

I was also thinking of a simple standalone http python like

1. GET http://ip:port/api/events?after=<now-1m>
2. get last item and save its <id>
3. if <id> is different than previous send over telegram the event together with  http://ip:port/api/events/<id>/clip.mp4
4. send last id
5. sleep(1m)

This could be even extended to include all the <id> that have never seen before but still it is more of a "delayed" notifications

**Comment by piwko28** [comment]
After some tests I decided to abandon that idea. The mobile app is not able to do it properly and it needs some solution on Frigate NVR side or additional servers. Some home automation systems can realize such integrations, like Home Assistant.
